export const comments = [
    ['cookies', 0, "Máte chuť dělat sušenky. Ale nikdo nechce jíst vaše sušenky."],
    ['cookies', 5, "Vaše první várka jde do koše. Sousedský mýval se ho sotva dotkne."],
    ['cookies', 5e1, "Vaše rodina souhlasí s vyzkoušením některých vašich cookies."],
    ['cookies', 1e2, "Vaše sušenky jsou oblíbené v okolí."],
    ['cookies', 5e2, "Lidé začínají mluvit o vašich sušenkách."],
    ['cookies', 1e3, "O vašich sušenkách se mluví na míle daleko."],
    ['cookies', 5e3, "Vaše sušenky jsou vyhlášené v celém městě!"],
    ['cookies', 1e4, "Tvoje sušenky přivedou všechny kluky na dvůr."],
    ['cookies', 5e4, "Vaše soubory cookie mají nyní své vlastní webové stránky!"],
    ['cookies', 1e5, "Vaše sušenky stojí hodně peněz."],
    ['cookies', 5e5, "Vaše cookies se velmi dobře prodávají ve vzdálených zemích."],
    ['cookies', 1e6, "Lidé přicházejí z velmi vzdálených míst, aby ochutnali vaše sušenky."],
    ['cookies', 5e6, "Na vašich sušenkách si pochutnávají králové a královny z celého světa."],
    ['cookies', 1e7, "Nyní existují muzea věnovaná vašim sušenkám."],
    ['cookies', 5e7, "Na počest vašich cookies byl vytvořen národní den."],
    ['cookies', 1e8, "Vaše cookies byly označeny za součást divů světa."],
    ['cookies', 5e8, "Historické knihy nyní obsahují celou kapitolu o vašich cookies."],
    ['cookies', 1e9, "Vaše soubory cookie byly umístěny pod vládní dohled."],
    ['cookies', 5e9, "Na vašich sušenkách si pochutnává celá planeta!"],
    ['cookies', 1e10, "Podivná stvoření ze sousedních planet chtějí ochutnat vaše sušenky."],
    ['cookies', 5e10, "Starší bohové z celého vesmíru se probudili, aby ochutnali vaše sušenky."],
    ['cookies', 1e11, "Bytosti z jiných dimenzí pronikají do existence, jen aby ochutnaly vaše sušenky."],
    ['cookies', 5e11, "Vaše soubory cookie dosáhly sentience."],
    ['cookies', 1e12, "Vesmír se nyní proměnil v těsto na sušenky na molekulární úroveň."],
    ['cookies', 5e12, "Vaše soubory cookie přepisují základní zákony vesmíru."],
    ['cookies', 1e13, "Místní zpravodajská stanice spustí 10minutový segment o vašich souborech cookie. Úspěch!"],
    ['cookies', 1e13, "je čas přestat hrát"],

    ['cookies', 1e4, "Novinky : soubory cookie byly testovány na zvířeti, nebyly zjištěny žádné škodlivé účinky."],
    ['cookies', 1e4, "Novinky: sušenky nečekaně populární mezi zvířaty!"],
    ['cookies', 1e4, "Novinky: nevzhledné hrudky nalezené na zvířeti poblíž zařízení na sušenky: V podstatě tak vždy vypadali, říká biolog."],
    ['cookies', 1e4, "Novinky: Sušenky se hodí k pečenému zvířátku, říká kontroverzní šéfkuchař."],
    ['cookies', 1e4, "Novinky : vědec předpovídá bezprostřední „konec světa“ související s cookies; se mezi vrstevníky stává vtipem."],
    ['cookies', 1e4, "Novinky : Muž vyloupil banku, koupil sušenky."],
    ['cookies', 1e4, "Novinky : díky čemu mají sušenky tak správnou chuť? Pravděpodobně všechny, co do nich dali, říká anonymní tipař."],
    ['cookies', 1e4, "Novinky : u muže zjištěn alergii na sušenky; Jaký podivín, říká rodina."],
    ['cookies', 1e4, "Zprávy : zahraniční politik zapojený do skandálu s pašováním sušenek."],
    ['cookies', 1e4, "Novinky : město postihuje nedostatek sušenek, lidé jsou nuceni jíst koláčky; „jen ne totéž“, připouští starosta."],
    ['cookies', 1e4, "Novinky: Musíte uznat, že všechny ty sušenky jsou trochu zlověstné, říká zmatený idiot."],
    ['cookies', 1e4, "Novinky : film zrušen pro nedostatek herců: všichni jsou doma a jedí sušenky, lamentuje ředitel."],
    ['cookies', 1e4, "Novinky: komik byl nucen zrušit rutinu používání cookies kvůli nesouvisejícím zažívacím potížím."],
    ['cookies', 1e4, "Novinky: Nové náboženství založené na cookies zachvátilo celý národ."],
    ['cookies', 1e4, "Zprávy: Fosilní záznamy ukazují organismy založené na cookies převládající během kambrické exploze, říkají vědci."],
    ['cookies', 1e4, "Novinky : zabaveny záhadné nelegální cookies; chutná hrozně, říká policie."],
    ['cookies', 1e4, "Novinky : muž nalezen mrtvý po požití sušenky; vyšetřovatelé upřednostňují hypotézu „mafiánského únosce“."],
    ['cookies', 1e4, "News: vesmír se do značné míry zacyklí sám do sebe, navrhuje výzkumník: Jsou to sušenky až dolů."],
    ['cookies', 1e4, "Novinky : menší incident související s cookies promění celé město v popel; sousední města požádala o čipování pro rekonstrukci."],
    ['cookies', 1e4, "Novinky: Jsou naše média kontrolována průmyslem cookies? Klidně by tomu tak mohlo být, říká potrhlý konspirační teoretik."],
    ['cookies', 1e4, "Novinky: Soubory cookie oblíbené mezi všemi věkovými skupinami, včetně plodů, říká studie.;"],
    ['cookies', 1e4, "Novinky: V centru města se otevírá restaurace plná cookies. Pokrmy, jako jsou dušené sušenky, sušenkový termidor a jako dezert: palačinky."],
    ['cookies', 1e4, "Novinky: Soubory cookie by mohly být klíčem k teleportaci, říkají vědci."],
    ['cookies', 1e4, "Novinky: Dobře, říká dotazovaný orangutan."],
    ['cookies', 1e4, "Novinky : jak chutnají zlaté sušenky? Studie odhaluje příchuť „někde mezi mátou klasnatou a lékořicí“."],
    ['cookies', 1e4, "Novinky : jak chutnají sušenky hněvu? Studie odhaluje příchuť „někde mezi krvavou klobásou a mořskou vodou“."],
    ['cookies', 1e4, "Zprávy : lidé na celém internetu se stále škrábou na hlavě nad nesmyslným odkazem: Dobře, ale proč vejce?"],
    ['cookies', 1e4, "Novinky: virální video „Too Many Cookies“ by mohlo být „pochmurným komentářem k blížící se krizi, které se náš svět chystá čelit“, říká slavný ekonom."],
    ['cookies', 1e4, "Novinky : memy z minulého roku jsou stále aktuální, odsuzují odborníci."],
    ['cookies', 1e4, "Novinky: emotikony cookie nejoblíbenější mezi teenagery, daleko před „soudným znamením ruky OK“ a „proměnlivým temným měsícem“, říká studie."],
    ['cookies', 1e4, "Novinky : porody podezřele holohlavých dětí na vzestupu; reptiliánští vládci odmítají účast."],
    ['cookies', 1e4, "Novinky: „V tuto chvíli do ekonomiky prostupují cookies“, říká ekonom. Pokud začneme jíst něco jiného, jsme všichni mrtví."],
    ['cookies', 1e4, "Zprávy: slovní hříčka v titulku rozhořčuje město, vyvolává nepokoje. 21 zraněných, 5 mrtvých; starosta stále chybí."],
    ['cookies', 1e4, "Novinky: Soubory cookie jsou nyní v některých zaostalých zemích nezákonné. Rostoucí politické napětí; válka brzy, doufejme."],
    ['cookies', 1e4, "Zprávy: rozčiluje moderátora rádia bláboly o pixelovaných ikonách. Žádný ze sušenek není zarovnaný! Copak to nikdo jiný nevidí? Mám pocit, že beru šílené prášky!"],
    ['cookies', 1e4, "Novinky: přerostlé sušenky nalezené v rybářských sítích vyvolávají otázky ohledně pečení hormonů."],
    ['cookies', 1e4, "Novinky: Je na Marsu život? Různí výrobci čokoládových tyčinek jsou v současnosti vyšetřováni kvůli bakteriálním kontaminantům."],
    ['cookies', 1e4, "Novinky: Takže myslím, že to je teď věc, komentuje vědec částečky sušenek, které jsou nyní přítomny prakticky ve všech ocelích vyrobených od doby, kdy se celosvětově zvýšila výroba sušenek."],
    ['cookies', 1e4, "Novinky: stopová množství částic sušenek zjištěná u většiny živých tvorů, z nichž některé je adaptují jako součást nových a exotických metabolických procesů."],
]