export const grandmaNames = [
    "I love my cookies",
    "Grandma Chara",
    "Lukexzrs Grandma",
    "Claudia",
    "Jaema",
    "Harlow Diggs",
    "Ms Shelley",
    "Tobi Kummerer",
    "Tomato Pie",
    "Gramma Margaret",
    "Barack Obama",
    "Anneliese Albina Emma",
    "Samuel Robertson",
    "amogus",
    "latte",
    "majik",
    "Peggy Hattenfels",
    "Mason W",
    "YeOlGrammityGram",
    "Help me",
    "Yackemflam",
    "DRIFTER1117",
    "Berit",
    "the book was empty",
    "Amma Jóna",
    "binbinuser",
    "ɐwpuɐɹפ",
    "Cthulhu",
    "Brooke Chumbers",
    "BoShek",
    "Autosuffisant",
    "Rivne",
    "Lady Sweets",
    "Megan I. McIntosh",
    "Olive Gardenia",
    "Galadion",
    "ipm1234",
    "200rassberris",
    "Mamie Cobol",
    "Betty BeardPuller",
    "Grandma Divah",
    "Ians Mom",
    "WillStreet",
    "Ms. Cppkies",
    "Fmaily Gyu funy momens #420",
    "lickin my cookie",
    "Loremaster Rawlins",
    "Polar",
    "David loves Rachel! <3",
    "SkeletonJoke",
    "Aku daikan",
    "Baker of Steak Cookies",
    "Vovó Dal",
    "Vivian",
    "Granny Grearest",
    "Joe Grandmomma",
    "E",
    "hosh...",
    "Annuziatta",
    "Grandmommy Celestine",
    "Nikola",
    "Leota Marie",
    "amdnarG",
    "Velma Francis",
    "VenMissa",
    "Ume Ito",
    "Tanyac Crimson",
    "ScartTheWaz",
    "Matt Was Here",
    "Only 30 characters, huh? Fine.",
    "Nasus",
    "Addison Bennett",
    "Cookie maker 100",
    "Eggy Grandma",
    "Her",
    "Ruby Wrinkle",
    "Lurking Tealeaf",
    "The Worm Which Waits",
    "Nonmoving Osmond",
    "Hanna Highmark",
    "Granny Jonathan",
    "Groz",
    "Error 404: Name not Found",
    "Falling Collin",
    "He Had Boxing Gloves On",
    "Ashlee <3",
    "Aviators",
    "Fey Yoshida",
    "Alireah",
    "moist butterscotch lips",
    "Caden",
    "Matthue Loose",
    "Exterminator",
    "DevilishWarrior",
    "Linda-Bea Dolvoy",
    "noisypineapples",
    "Tyler Liddick",
    "Henrietta Gertrude",
    "Kimahri",
    "Tell Cersei, it was me.",
    "Elder Pledge 666x in a row...",
    "Jarvis Fishwick",
    "Kage",
    "Doctergreen",
    "Benny Zhy",
    "Audrey Porter",
    "SERAS FAMO!!!",
    "Barbara",
    "BUT IT WAS ME, DIO!",
    "Deborah Wright",
    "Grackitz",
    "Pikachi",
    "Swamper",
    "Pielak",
    "Anneliese",
    "Geuser",
    "Miyori Grandma",
    "Ruby Rose",
    "Satans grandmother",
    "Felpinhazinha",
    "Chlorophyte Grandma",
    "Betty Margaret Davis",
    "A Duplicate Grandma",
    "Baker? I hardly know her!",
    "Youre Killing Me Smols",
    "Ittle Dew",
    "Audrey",
    "Mirle",
    "Alex",
    "Sanda Reiss",
    "Grandma Kara",
    "Tammie",
    "?????",
    "Idling Vasha",
    "Ms. Denis Gur Arie",
    "EEEEEE",
    "Kiwibajs",
    "Freya28",
    "Cora",
    "Hey guys, its Nicole",
    "Penka",
    "Anne",
    "Shiny Blue Grandma",
    "Carmelina",
    "Turtlenator",
    "TechhX",
    "Cookieatron4000",
    "Eanydo Erdman",
    "MinionMemer",
    "Elisabeth",
    "Tandy",
    "Kamilla",
    "Chris",
    "Krieg",
    "Dan",
    "Grandma Jones",
    "Oda",
    "Tesco employee #65",
    "Rosie Beestinger",
    "Benyboy",
    "Stacys Grandma",
    "Erina Pendleton-Joestar",
    "Gerry",
    "Dauna",
    "Dont Stop Me Now",
    "Ms. Chievous",
    "Aryll",
    "Hey guys, Dexterfan99 here",
    "Khookiesi, Grandmother of Dragonflights",
    "The Roach Queen",
    "Zan Tart-izanne",
    "Nakamoto",
    "Mrs. Fizzwidget",
    "Granny Rags",
    "Forgotten Abbey",
    "Knitting Slave",
    "Starco",
    "Cosma-Tanti",
    "Izual Rebirth",
    "Lieselotte",
    "Koisuru Fortune Grandma",
    "DAF Pvnk - Mother of trucks",
    "Fanny",
    "Steve...?",
    "Ahtelo",
    "How did you find me, JUNESUK?",
    "Bear",
    "Euphegenia Doubtfire",
    "Rydh",
    "Her?",
    "Jeff Junior",
    "Aune Mummo",
    "La mere Michel",
    "The GrandNut",
    "Carmelina Calabrese",
    "dQw4w9WgXcQ",
    "Mamichette",
    "The First Baker",
    "Tjien Nio",
    "Betty Ann Niemi",
    "Survivor of the Stale",
    "Mrs Sugai Kirin",
    "Mrs PoopyButthole",
    "Lily Bowen",
    "Moondoge",
    "Telos",
    "Psychedelic Rapper Andrew JD",
    "Meep Moop",
    "Swad Plan",
    "SneakySquid",
    "Grandma #42",
    "Babayaga",
    "Rose",
    "Ivy",
    "Natsuki",
    "Jet-dayo",
    "egg Sr.",
    "Charlie",
    "Grandma McGrandmaface",
    "Gabrielle",
    "Janice",
    "Patreona",
    "Granny",
    "Gusher",
    "Ethel",
    "Edna",
    "Doris",
    "Maud",
    "Hilda",
    "Gladys",
    "Michelle",
    "Michele",
    "Phyllis",
    "Millicent",
    "Muriel",
    "Myrtle",
    "Mildred",
    "Mavis",
    "Helen",
    "Gloria",
    "Sheila",
    "Betty",
    "Gertrude",
    "Agatha",
    "Beryl",
    "Agnes",
    "Pearl",
    "Precious",
    "Ruby",
    "Vera",
    "Bonnie",
    "Ada",
    "Bunny",
    "Cookie",
    "Darling",
    "Gaga",
    "GamGam",
    "Memaw",
    "Mimsy",
    "Peanut",
    "Nana",
    "Nan",
    "Tootsie",
    "Warty",
    "Stinky",
    "Heinous"
];